### ISSUE TITLE
Wi-Fi credentials with spaces fail

### ISSUE THREAD

**Issue by phoddie** [ralphwetzel/node-red-mcu-plugin#18]
When using a Wi-Fi SSID or password that contains spaces, the MCU plug-in generates an invalid command line. For example, if the SSID is "Moddable WiFi" this is the command line:

```
mcconfig -d -x localhost:5004 -m -p esp/nodemcu ssid=Moddable WiFi password=xyzzy
```

The correct command line is:
```
mcconfig -d -x localhost:5004 -m -p esp/nodemcu ssid="Moddable WiFi" password=xyzzy
```

A password with spaces fails in the same way.

I tried putting entering quotes in the "WiFi | SSID" field, but they are removed.

**Comment by ralphwetzel** [comment]
Thank you for reporting this!
Should be fixed now by a commit a few minutes ago.
Would be great if you find time to give it a try...

**Comment by phoddie** [comment]
Thanks. That works much better.

FWIW – It  fails for values that contain `"` or `'`' but that's probably enough of an edge case that it isn't worth addressing now.

**Comment by ralphwetzel** [comment]
> It fails for values that contain `"` or `'`'...

Thank you for this heads-up. You're fully right.
I've [refactored it once again](https://github.com/ralphwetzel/node-red-mcu-plugin/commit/639baccd8068e0052b49ca8683419082784008b2) - to omit dancing with the oddities of the various command lines. Handover of this data is now performed via the config arguments in the `manifest.json`.

**Comment by phoddie** [comment]
Thanks for taking care of that. It is enough of an edge case that I didn't expect it!
