### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by MatsA** [ralphwetzel/node-red-mcu-plugin#33]
Doing my first build on a RPi, Bullseye, and Node-Red 3.0.2 I get the error as below.

The mentioned rule is found at => ./pico/pico-sdk/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.pio

/Mats 

***
Starting build process...
Host system check: #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023
MCU Build system check: p1.2.1-post + #f2f2c68 @ m3.7.6-8-g746d137
HOME directory check: /home/pi
Creating build environment for platform pico/pico_w.
Working directory: /home/pi/.node-red/mcu-plugin-cache/tns8c0j9h9b
$PICO_GCC_ROOT identified: /usr
$PICO_SDK_DIR identified: /home/pi/pico/pico-sdk
cd /home/pi/.node-red/mcu-plugin-cache/tns8c0j9h9b
Creating build script file...
/bin/bash ./build.sh
mcconfig -d -x localhost:5004 -m -p pico/pico_w
make: *** No rule to make target '/home/pi/pico/pico-sdk/src/rp2_common/cyw43_driver/cyw43_bus_pio_spi.pio', needed by '/home/pi/Projects/moddable/build/tmp/pico/pico_w/debug/tns8c0j9h9b/cyw43_bus_pio_spi.pio.h'.  Stop.

**Comment by ralphwetzel** [comment]
There's a [discussion](https://github.com/Moddable-OpenSource/moddable/discussions/1049) in the Moddable repo that looks like an [answer to this topic](https://github.com/Moddable-OpenSource/moddable/discussions/1049#discussioncomment-5109880): 

You need to (continue to) use Pico SDK 1.4.
Pico SDK 1.5 currently seems to be not supported by the Moddable SDK.

**Comment by MatsA** [comment]
Thanks that helped !
Did some googling but didn't found the issue you pointed out.

Now it works but the console monitor hangs at `Waiting for copy to complete...........` despite that the code is fully downloaded and executes at the Pico. But that seems to be a Moddable problem ? 

/Mats
